code_set:
  arch: horiz
  code: LDPC64x128
  dec: bp
  it: 10
  path: codes
load_set:
  fn_sim: RES_
  fn_train: trainhist_
  gpu: 1
  prec: float64
  sim: 0
  sv_ext: npz
  train: 1
sim_set:
  L: 64
  Mod: QPSK
  Nbatch: 10000
  Nerr_min: 1000
  Nr: 64
  Nt: 64
  algo: CMD
  binopt: 1
  ebn0_range:
  - -6
  - 36
  fn_ext: _binary_tau0.1
  path: curves
  rho:
  - 0
  - 120
  - 0.5
  sim_prec: 5.0e-07
  snr_grid: 1
train_set:
  Nepoch: 0
  batch_size: 500
  dnndepth: 2
  dnnverbose: 2
  dnnwidth: 512
  ebn0_range:
  - 4
  - 27
  esteps: 0
  it_checkp: 100
  lr_dyn:
    boundaries:
    - 1000
    - 3000
    mode: 0
    values:
    - 0.001
    - 0.0001
    - 1.0e-05
  multiloss: 0
  online: 0
  opt: adam
  sel_bweights: 0
  soft: 0
  start_point: default
  sv_checkp: 1
  val_size: 10000
