code_set:
  arch: horiz
  code: uncoded
  dec: bp
  it: 10
  path: codes
load_set:
  fn_sim: RES_
  fn_train: trainhist_
  gpu: 1
  prec: float32
  sim: 1
  sv_ext: npz
  train: 1
sim_set:
  L: 64
  Mod: QPSK
  Nbatch: 10000
  Nerr_min: 1000
  Nr: 128
  Nt: 64
  algo: CMD
  binopt: 1
  ebn0_range:
  - -6
  - 36
  fn_ext: _binary_snr4_11
  path: curves
  rho:
  - 20
  - 120
  sim_prec: 1.0e-07
  snr_grid: 1
train_set:
  Nepoch: 100000
  batch_size: 500
  ebn0_range:
  - 8
  - 8
  esteps: 0
  it_checkp: 1
  lr_dyn: 0
  multiloss: 0
  online: 0
  opt: adam
  sel_bweights: 0
  soft: 0
  start_point: load
  sv_checkp: 1
  val_size: 10000
