code_set:
  arch: horiz
  code: uncoded
  dec: bp
  it: 10
  path: codes
load_set:
  fn_sim: RES_
  fn_train: trainhist_
  gpu: 1
  prec: float64
  sim: 0
  sv_ext: npz
  train: 0
sim_set:
  L: 8
  Mod: QPSK
  Nbatch: 10000
  Nerr_min: 1000
  Nr: 8
  Nt: 8
  algo: AMP
  binopt: 1
  ebn0_range:
  - -6
  - 36
  fn_ext: _OneRing20
  path: curves
  rho: 20
  sim_prec: 5.0e-07
  snr_grid: 1
train_set:
  Nepoch: 100000
  batch_size: 500
  ebn0_range:
  - 4
  - 27
  esteps: 0
  it_checkp: 100
  lr_dyn: 0
  multiloss: 0
  sel_bweights: 0
  soft: 0
  start_point: default
  sv_checkp: 1
  val_size: 10000
